### ISSUE TITLE
Unexpected Error during setup of integration

### ISSUE THREAD

**Issue by Schlange1337** [Kleinrotti/hass-senertec#13]
Hi Kleinrotti, 

I installed your integration today and tried to integrate my Dachs. Sadly I get an unexpected error. I activated the log and got this:

`2024-12-25 17:35:55.718 DEBUG (MainThread) [custom_components.senertec.config_flow] Trying to connect to senertec during setup
2024-12-25 17:35:55.723 INFO (SyncWorker_7) [senertec.client] Logging in..
2024-12-25 17:35:56.193 INFO (SyncWorker_7) [senertec.client] Login was successful.
2024-12-25 17:35:56.195 INFO (SyncWorker_0) [senertec.client] Initializing senertec platform...
2024-12-25 17:35:56.860 ERROR (MainThread) [custom_components.senertec.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/senertec/config_flow.py", line 78, in async_step_user
    info = await validate_connection(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/senertec/config_flow.py", line 45, in validate_connection
    await hass.async_add_executor_job(client.connectUnit, units[0].serial)
                                                          ~~~~~^^^
IndexError: list index out of range
2024-12-25 17:35:56.917 INFO (senertec-websocket) [websocket] Websocket connected
2024-12-25 17:35:56.920 INFO (senertec-websocket) [senertec.client] Connected to Senertec websocket `


My Dachs is a HKA-G S2

any Idea why I get this error? 

 Thank you in advance!

**Comment by Kleinrotti** [comment]
Seems to be the same problem like this [one](https://github.com/Kleinrotti/hass-senertec/issues/11)
After the login no devices are returned, therefore the error is an empty list without any device.

**Comment by Schlange1337** [comment]
Thank you for your quick response, I will get in contact with senertec and will report back if it helps. :-)

**Comment by Schlange1337** [comment]
Hi, sorry for the late reply. After getting in contact with the support it works fine now. Thank you for this nice integration :)
