### ISSUE TITLE
Object has no attribut

### ISSUE THREAD

**Issue by DieSeef** [Kleinrotti/hass-senertec#6]
Hi,
installed the Senertec integration and added the correct DachsPortal2 credentials but getting the below error:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/senertec/__init__.py:51 
Integration: Senertec Energy Systems (documentation, issues) 
First occurred: 19:51:35 (1 occurrences) 
Last logged: 19:51:35

Error setting up entry Senertec for senertec
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/senertec/__init__.py", line 51, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

2023-05-27 19:51:10.865 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration senertec which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-27 19:51:26.625 INFO (SyncWorker_5) [senertec.client] Logging in..
2023-05-27 19:51:27.904 INFO (SyncWorker_5) [senertec.client] Login was successful.
2023-05-27 19:51:27.905 INFO (SyncWorker_5) [senertec.client] Initializing senertec platform...
2023-05-27 19:51:28.834 INFO (senertec-websocket) [senertec.client] Connected to Senertec websocket
2023-05-27 19:51:35.281 INFO (SyncWorker_3) [senertec.client] Logging out..
2023-05-27 19:51:35.546 INFO (senertec-websocket) [senertec.client] Senertec Websocket closed with code None
2023-05-27 19:51:35.555 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Senertec for senertec
File "/config/custom_components/senertec/__init__.py", line 51, in async_setup_entry

**Comment by DieSeef** [comment]
Update to latest integartion version fixed the issue
